version: '3'

services:
  workflow-modeler:
    image: planqk/workflow-modeler:latest
    ports:
      - 8080:8080
    networks:
      - qunicorn-tutorial
  camunda-engine:
    image: camunda/camunda-bpm-platform:run-7.19.0
    ports:
      - 8090:8080
    networks:
      - qunicorn-tutorial
  qunicorn:
      image: "ghcr.io/sequenc-consortium/qunicorn-core:main"
      networks:
        - qunicorn-tutorial
      environment:
        CONTAINER_MODE: server
        SERVER_PORT: 5005
        BROKER_URL: "redis://broker:6379"
        DB_URL: "postgresql://postgres:passwd@postgres/qunicorn"
        JWKS_URL: "http://keycloak:8081/auth/realms/qunicorn/protocol/openid-connect/certs"
        NUMBA_CACHE_DIR: "/app/cache"
      depends_on:
        - postgres
        - broker
      ports:
        - "5005:5005"

  worker:
    image: "ghcr.io/sequenc-consortium/qunicorn-core:main"
    networks:
      - qunicorn-tutorial
    environment:
      CONTAINER_MODE: worker
      BROKER_URL: "redis://broker:6379"
      DB_URL: "postgresql://postgres:passwd@postgres/qunicorn"
      NUMBA_CACHE_DIR: "/app/cache"
    depends_on:
      - postgres
      - broker
    ports:
      - "6379"

  keycloak:
    image: jboss/keycloak
    networks:
      - qunicorn-tutorial
    depends_on:
      - keycloak_postgres
    ports:
      - "8081:8080"
    volumes:
      - "./resources/keycloak-realm-export.json:/tmp/realm-export.json"
    environment:
      DB_VENDOR: postgres
      KEYCLOAK_USER: kc_user
      KEYCLOAK_PASSWORD: kc_pass
      DB_ADDR: keycloak_postgres
      DB_USER: postgres
      DB_PASSWORD: passwd
      KEYCLOAK_IMPORT=/tmp/realm-export.json:

  keycloak_postgres:
    image: postgres:15.3
    networks:
      - qunicorn-tutorial
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data \


  broker:
    image: redis:7.0.12
    networks:
      - qunicorn-tutorial
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15.3
    networks:
      - qunicorn-tutorial
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: qunicorn
    volumes:
      - pgdata:/var/lib/postgresql/data \
    ports:
      - "5432:5432"

networks:
  qunicorn-tutorial:
    driver: bridge

volumes:
  pgdata:
  keycloak_pgdata:
