version: '3'
services:

  # Standard setup based on OpenTosca Docker for the deployment-view plugin demo

  qunicorn:
      image: "iaasgeorgdl/qunicorn:release.11.23"
      networks:
        - qunicorn-tutorial
      environment:
        CONTAINER_MODE: server
        SERVER_PORT: 5005
        BROKER_URL: "redis://broker:6379"
        DB_URL: "postgresql://postgres:passwd@postgres/qunicorn"
        JWKS_URL: "http://keycloak:8081/auth/realms/qunicorn/protocol/openid-connect/certs"
        NUMBA_CACHE_DIR: "/app/cache"
      depends_on:
        - postgres
        - broker
        - worker
      ports:
        - "5005:5005"


  worker:
    image: "iaasgeorgdl/qunicorn:release.11.23"
    networks:
      - qunicorn-tutorial
    environment:
      CONTAINER_MODE: worker
      BROKER_URL: "redis://broker:6379"
      DB_URL: "postgresql://postgres:passwd@postgres/qunicorn"
      NUMBA_CACHE_DIR: "/app/cache"
    depends_on:
      - postgres
      - broker
    ports:
      - "6379"

  # Standard Keycloak container, realm export is the qunicorn realm
  keycloak:
    image: jboss/keycloak
    networks:
      - qunicorn-tutorial
    depends_on:
      - keycloak_postgres
    ports:
      - "8091:8080"
    volumes:
      - "./resources/keycloak-realm-export.json:/tmp/realm-export.json"
    environment:
      DB_VENDOR: postgres
      KEYCLOAK_USER: kc_user
      KEYCLOAK_PASSWORD: kc_pass
      DB_ADDR: keycloak_postgres
      DB_USER: postgres
      DB_PASSWORD: passwd
      KEYCLOAK_IMPORT=/tmp/realm-export.json:

  # Database for the keycloak realms and users
  keycloak_postgres:
    image: postgres:15.3
    networks:
      - qunicorn-tutorial
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data \

  # Broker for the Celery (Pilot-Job) setup 
  broker:
    image: redis:7.0.12
    networks:
      - qunicorn-tutorial
    ports:
      - "6379:6379"

  # postgres container for the database for Qunicorn jobs and deployments
  postgres:
    image: postgres:15.3
    networks:
      - qunicorn-tutorial
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: qunicorn
    volumes:
      - pgdata:/var/lib/postgresql/data \
    ports:
      - "5432:5432"

  # Unified to the network, also tosca containers
networks:
  qunicorn-tutorial:
    driver: bridge

volumes:
  pgdata:
  keycloak_pgdata:

